# Generated by Django 4.1.2 on 2024-04-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('fec_nac', models.DateField()),
                ('correo', models.CharField(max_length=40)),
                ('contra', models.CharField(max_length=40)),
            ],
        ),
    ]
