# Generated by Django 4.1.2 on 2024-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('cod_pedido', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fec_ped', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_prod', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fec_res', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tipo_usuario',
            fields=[
                ('id_tipo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
    ]
