# Generated by Django 4.1.2 on 2024-04-23 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0003_medio_pago_alter_tipo_usuario_id_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PaginaWeb.tipo_usuario'),
        ),
    ]
