# Generated by Django 5.0.6 on 2024-05-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0005_usuario_reserva_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/Imagenes/Imgs_subidas'),
        ),
    ]
