# Generated by Django 5.0.6 on 2024-05-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='PaginaWeb/static/Imagenes/Imgs_subidas'),
        ),
    ]
