# Generated by Django 5.0.6 on 2024-06-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0010_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_usuario',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='pedido_producto',
            name='cod_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido_producto',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedido_usuario',
            name='cod_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido_usuario',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario_reserva',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario_reserva',
            name='id_reserva',
        ),
        migrations.DeleteModel(
            name='medio_pago',
        ),
        migrations.DeleteModel(
            name='pedido_producto',
        ),
        migrations.DeleteModel(
            name='pedido_usuario',
        ),
        migrations.DeleteModel(
            name='tipo_usuario',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.DeleteModel(
            name='usuario_reserva',
        ),
    ]
