# Generated by Django 5.0.6 on 2024-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0012_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CF', 'Cafés'), ('SW', 'Sandwiches'), ('TG', 'Tragos'), ('PCT', 'Picoteos'), ('TT', 'Tortas'), ('PTR', 'Postres'), ('EX', 'Extras'), ('OTR', 'Otros')], default='OTR', max_length=15),
        ),
    ]
