# Generated by Django 5.0.6 on 2024-06-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0013_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=15),
        ),
    ]
