# Generated by Django 5.0.6 on 2024-06-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0014_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categ', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cod_categ', models.CharField(max_length=5)),
                ('nom_categ', models.CharField(max_length=30)),
            ],
        ),
    ]
