# Generated by Django 5.0.6 on 2024-07-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0016_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cod_pedido_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaWeb.pedido')),
                ('id_prod_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaWeb.producto')),
            ],
        ),
    ]
